{
 "title": "Consul Server Monitoring from grafana Peter 20220119",
 "description": "Maintained by the Consul team at HashiCorp. Displays critical health metrics about Consul servers, which are key to understanding Consul servers' behavior and stability in production. Also offers pre-built sections and panels for understanding usage of Consul by feature such as: KVs, DNS, the Catalog, and ACLs.",
 "tags": [
  "consul",
  "hashicorp"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "site", "label": "Data Center", "query": { "query": "consul_kvs_apply" } },
   {
    "name": "consul",
    "query": {
     "query": "label_values(consul_memberlist_gossip_sum, instance)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# servers in cluster",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COUNT (changes(consul_memberlist_gossip_sum[1m]) > 0) BY (labels)"
    }
   ]
  },
  {
   "title": "Raft Commit Time (p95)",
   "type": "stat",
   "description": "avg(consul_raft_commitTime_95_percentile)",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(max(consul_raft_commitTime{quantile=\"0.9\"}))"
    }
   ]
  },
  {
   "title": "Runtime Total GC Pause",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(consul_runtime_total_gc_pause_ns[5m]))"
    }
   ]
  },
  {
   "title": "Raft Leader Last Contact",
   "type": "stat",
   "description": "avg(max(consul_raft_leader_lastContact{quantile=\"0.9\"}))",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(max(consul_raft_leader_lastContact{quantile=\"0.9\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KV Apply Time (mean)",
   "type": "stat",
   "description": "sum(avg_over_time(consul_kvs_apply[1m])) by (instance)",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(consul_kvs_apply_count[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft Index Difference",
   "type": "stat",
   "description": "This will show 1 in the case of 0, that is because of Grafana saying \"UNHEALTHY\" which is untrue.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(max(consul_raft_last_index) - min(consul_raft_last_index))+1"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "options": {
    "content": "# Overview\n\nThe key metric for Consul health is KV Apply Time, which represents the write latency and throughput of the entire cluster.\n\nMean KV Apply Time < 3,000ms is considered Healthy. < 1,000ms is ideal.\n\nSee graph at right for current status."
   }
  },
  {
   "title": "Services and Instances",
   "type": "timeseries",
   "description": "Measures the current number of unique services and service instances registered with Consul. Only emitted by Consul servers. Instances added in v1.9.0.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "max(consul_consul_state_service_instances)",
     "legendFormat": "Service Instances"
    },
    {
     "expr": "max(consul_consul_state_services)",
     "legendFormat": "Services"
    }
   ]
  },
  {
   "title": "Transaction Timing - should be consistent; a few ms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Autopilot Health",
   "type": "stat",
   "description": "A boolean value that will show 1 if there are no issues, and 0 if autopilot has detected an issue. First, ensure that the cluster has an operational leader. If so, ensure that all nodes have sufficient IO throughput and memory.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(consul_autopilot_healthy !=0 )",
     "legendFormat": "{{instance}} Healthy"
    }
   ]
  },
  {
   "title": "Transaction Apply Time",
   "type": "graph",
   "description": "Measures the time spent applying a transaction operation.\n\nNOTE: If there are too many timeseries here from clients, consider filtering down to server hosts. You can set this with a prometheus scrape target based on the node's role.",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_txn_apply{quantile=\"0.9\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft Transaction Apply Time",
   "type": "graph",
   "description": "TODO Interrogate the rate interval more\nRate of raft commits per server cluster. The commit count is emitted by the leader and can be considered authoritative across a datacenter.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(consul_raft_apply[${interval}]) >0",
     "legendFormat": "{{instance}} Transactions"
    }
   ]
  },
  {
   "title": "Raft Commit Time",
   "type": "graph",
   "description": "Measures the time it takes to commit a new entry to the Raft log on the leader.\n\nNOTE: If there are too many timeseries here from clients, consider filtering down to server hosts. You can set this with a prometheus scrape target based on the node's role.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_raft_commitTime{quantile=\"0.9\"} >0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KV Apply Time",
   "type": "graph",
   "description": "This measures the time it takes to complete an update to the KV store.\n\nNOTE: If there are too many timeseries here from clients, consider filtering down to server hosts. You can set this with a prometheus scrape target based on the node's role.\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_kvs_apply{quantile=\"0.9\"} !=0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consul Server Cluster Health - Leadership and Autopilot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "Autopilot Fault Tolerance w/o RZ",
   "type": "stat",
   "description": "0 is bad, 1 is ok, >1 is good\nNumber of voting servers that the local server cluster can lose while continuing to function.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(consul_autopilot_failure_tolerance >=0 )",
     "legendFormat": "{{instance}} Healthy"
    }
   ]
  },
  {
   "title": "Raft Leader Last Contacted",
   "type": "graph",
   "description": "Shows the duration since an agent had last seen the leader. Spikes here may indicate network issues or a leader slowing or becoming unavailable.",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_raft_leader_lastContact {quantile=\"0.9\"} > 0",
     "legendFormat": "{{instance}} lastContact"
    }
   ]
  },
  {
   "title": "Raft Election Events - stack",
   "type": "graph",
   "description": "This panel should show \"`No data`\" in a stable cluster. Some leadership transition events are expected, such as during cluster upgrades. Unexpected events may indicate an issue with cluster stability. ",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "consul_raft_state_candidate >0", "legendFormat": "{{instance}} Candidate" },
    { "expr": "consul_raft_state_leader >0", "legendFormat": "{{instance}} Leader" }
   ]
  },
  {
   "title": "Runtime Total GC Pause per 1m",
   "type": "graph",
   "description": "~ ns is normal\n> 2s/minute is not good\n> 5s/min is bad\nNumber of nanoseconds consumed by stop-the-world garbage collection (GC) pauses since Consul started.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(consul_runtime_total_gc_pause_ns[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consul Raft AppendEntries RPC",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(consul_raft_replication_appendEntries_rpc{quantile=\"0.99\"})",
     "legendFormat": "AppendEntries RPC p99 {{ peer_id}}"
    },
    {
     "expr": "avg(consul_raft_replication_appendEntries_rpc_sum/consul_raft_replication_appendEntries_rpc_count)",
     "legendFormat": "AppendEntris RPC mean {{ peer_id}}"
    },
    {
     "expr": "avg(consul_raft_rpc_appendEntries{quantile=\"0.99\"})",
     "legendFormat": "AppendEntries p99 {{host}}"
    },
    {
     "expr": "avg(consul_raft_rpc_appendEntries_sum / consul_raft_rpc_appendEntries_count)",
     "legendFormat": "AppendEntries mean {{host}}"
    },
    {
     "expr": "avg(consul_raft_rpc_appendEntries_storeLogs{quantile=\"0.99\"})",
     "legendFormat": "storeLogs p99 {{ host }}"
    },
    {
     "expr": "avg(consul_raft_rpc_appendEntries_storeLogs_sum / consul_raft_rpc_appendEntries_storeLogs_count)",
     "legendFormat": "storeLogs mean {{ host }}"
    }
   ]
  },
  {
   "title": "Network Activity - RPC Count - current load created from Agents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "title": "Consul RPC Query Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({__name__=~\"consul_rpc_query.*\"}[${interval}])",
     "legendFormat": "{{instance}} rpc queries"
    },
    {
     "expr": "rate(consul_client_rpc[${interval}])",
     "legendFormat": "{{instance}} client rpc queries"
    }
   ]
  },
  {
   "title": "Consul Client RPC Query Exceeded/Failed",
   "type": "graph",
   "description": "Increments whenever a Consul agent in client mode makes an RPC request to a Consul server\n* gets rate limited by that agent's limits configuration\n* or fails.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(consul_client_rpc_exceeded[${interval}])",
     "legendFormat": "{{instance}} exceeded"
    },
    {
     "expr": "rate(consul_client_rpc_failed[${interval}])",
     "legendFormat": "{{instance}} failed"
    }
   ]
  },
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "[TODO] Please ensure Consul has CPU, Disk, Memory, and Network bandwidth headroom available! We recommend creating panels here, querying your host stats for each.",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\".+\",name=~\"consul-.+\"}[$interval])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\"consul.+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Bytes Send and Received",
   "type": "graph",
   "description": "sum(rate(container_network_receive_bytes_total{image!=\"\",name=~\"consul-.*\"}[5m])) by (name)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",name=~\"consul-.*\"}[$interval])) by (name)",
     "legendFormat": "{{name}} recv"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{image!=\"\",name=~\"consul-.*\"}[$interval])) by (name)",
     "legendFormat": "{{name}} sent"
    }
   ]
  },
  {
   "title": "Consul Memory Usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "consul_runtime_alloc_bytes{instance=~\"consul-server.+\"}",
     "legendFormat": "{{instance}} alloc"
    },
    {
     "expr": "consul_runtime_sys_bytes{instance=~\"consul-server.+\"}",
     "legendFormat": "{{instance}} sys"
    }
   ]
  },
  {
   "title": "Network Packets Send and Received",
   "type": "graph",
   "description": "sum(rate(container_network_receive_bytes_total{image!=\"\",name=~\"consul-.*\"}[5m])) by (name)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{image!=\"\",name=~\"consul-.*\"}[$interval])) by (name)",
     "legendFormat": "{{name}} recv"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{image!=\"\",name=~\"consul-.*\"}[$interval])) by (name)",
     "legendFormat": "{{name}} sent"
    }
   ]
  },
  { "title": "Feature: DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "DNS Queries per interval",
   "type": "graph",
   "description": "Shows the rate of domain queries per node, bucketed into 5 minute intervals.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(consul_dns_domain_query_count[$interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "DNS Domain Query Time",
   "type": "graph",
   "description": "Shows the time spent handling a domain queries for each node. A spike here may indicate that there are too many concurrent domain queries, or the catalog is under high contention.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_dns_domain_query{quantile=\"0.9\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "DNS Reverse Query Time",
   "type": "graph",
   "description": "Show the time spent handling a reverse DNS query for the given node.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_dns_ptr_query{quantile=\"0.9\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Feature: KV Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Applies per 5m",
     "type": "graph",
     "description": "Shows the rate of KV operations in 5 minute buckets. ",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "ops/5m" } },
     "yaxes": [
      { "format": "ops/5m" }
     ],
     "targets": [
      {
       "expr": "rate(consul_kvs_apply_count[5m])"
      }
     ]
    },
    {
     "title": "KV Apply Time",
     "type": "stat",
     "description": "This measures the time it takes to complete an update to the KV store.\n\nNOTE: If there are too many timeseries here from clients, consider filtering down to server hosts. You can set this with a prometheus scrape target based on the node's role.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "consul_kvs_apply" }
     ]
    },
    {
     "title": "Transaction Apply Time",
     "type": "graph",
     "description": "Measures the time spent applying transaction operations.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "expr": "consul_txn_apply" }
     ]
    }
   ]
  },
  { "title": "Feature: ACLs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "ACL Resolves per 5min",
   "type": "graph",
   "description": "Counts how many ACL tokens are resolved and buckets them by 5 minute intervals. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ops/5m" } },
   "yaxes": [
    { "format": "ops/5m" }
   ],
   "targets": [
    {
     "expr": "rate(consul_acl_ResolveToken_count[5m])"
    }
   ]
  },
  {
   "title": "ACL ResolveToken Time",
   "type": "graph",
   "description": "Times how long it takes to resolve an ACL Token into its policies.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_acl_ResolveToken{quantile=\"0.9\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ACL Updates per 5m",
   "type": "graph",
   "description": "This counts the number of times we've updated an ACL, bucketed into 5 minute intervals.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ops/5m" } },
   "yaxes": [
    { "format": "ops/5m" }
   ],
   "targets": [
    {
     "expr": "rate(consul_acl_apply_count[5m])"
    }
   ]
  },
  {
   "title": "ACL Apply Time",
   "type": "graph",
   "description": "This measures the time it takes to complete an update to the ACL store.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_acl_apply{quantile=\"0.9\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Feature: Catalog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Catalog Operations per 5m",
   "type": "graph",
   "description": "This shows the rate of increase for catalog register and deregister operations. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ops/5m" } },
   "yaxes": [
    { "format": "ops/5m" }
   ],
   "targets": [
    {
     "expr": "rate(consul_catalog_register_count[5m])"
    },
    {
     "expr": "rate(consul_catalog_deregister_count[5m])"
    }
   ]
  },
  {
   "title": "Catalog Operation Time",
   "type": "graph",
   "description": "Measures the time it takes to complete catalog register or deregister operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_catalog_register{quantile=\"0.9\"}",
     "legendFormat": "{{instance}} register"
    },
    {
     "expr": "consul_catalog_deregister{quantile=\"0.9\"}",
     "legendFormat": "{{instance}} deregister"
    }
   ]
  },
  {
   "title": "Consul Leader",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "avg(consul_leader_reconcile)", "legendFormat": "consul.leader.reconcile p99" },
    { "expr": "avg(consul_leader_barrier)", "legendFormat": "consul.leader.barrier p99" },
    {
     "expr": "avg(consul_leader_reapTombstones)",
     "legendFormat": "consul.leader.reapTombstones p99"
    },
    {
     "expr": "avg(consul_leader_reconcileMember)",
     "legendFormat": "consul.leader.reconcileMember p99"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Go Routines by Server",
   "type": "graph",
   "description": "Tracks the number of running goroutines and is a general load pressure indicator. This may burst from time to time but should return to a steady state value.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"consul_runtime_num_goroutine.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consul RPC Health",
   "type": "graph",
   "description": "Increments when a server receives a read RPC request, indicating the rate of new read queries.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({__name__=~\"consul_rpc_query.*\"}[${interval}])",
     "legendFormat": "{{instance}} rpc.query"
    },
    {
     "expr": "rate(consul_rpc_request[${interval}])",
     "legendFormat": "{{instance}} rpc.request"
    },
    {
     "expr": "rate(consul_rpc_raft_handoff[${interval}])",
     "legendFormat": "{{instance}} rpc.raft.handoff"
    }
   ]
  },
  {
   "title": "Consul Finite State Machine (p99)",
   "type": "graph",
   "description": "fsm.apply The number of logs committed since the last interval.\nfsm.register - Measures the time it takes to apply a catalog register operation to the FSM.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(consul_fsm_txn{quantile=\"0.99\"})",
     "legendFormat": "fsm.txn p99"
    },
    {
     "expr": "avg(consul_fsm_kvs {quantile=\"0.99\"})",
     "legendFormat": "fsm.kvs p99"
    },
    {
     "expr": "avg(consul_fsm_coordinate_batch_update {quantile=\"0.99\"})",
     "legendFormat": "fsm.coordinate p99"
    },
    {
     "expr": "avg(consul_fsm_persist{quantile=\"0.99\"})",
     "legendFormat": "fsm.persist p99"
    },
    {
     "expr": "avg(consul_raft_fsm_apply{quantile=\"0.99\"})",
     "legendFormat": "fsm.apply p99"
    },
    {
     "expr": "avg(consul_fsm_register{quantile=\"0.99\"})",
     "legendFormat": "fsm.register p99"
    },
    {
     "expr": "avg(consul_fsm_deregister{quantile=\"0.99\"})",
     "legendFormat": "fsm.deregister p99"
    }
   ]
  },
  {
   "title": "Consul Finite State Machine (Count)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(consul_fsm_txn_count[${interval}]))",
     "legendFormat": "fsm.txn count"
    },
    {
     "expr": "avg(rate(consul_fsm_kvs_count[${interval}]))",
     "legendFormat": "fsm.kvs count"
    },
    {
     "expr": "avg(rate(consul_fsm_coordinate_count[${interval}]))",
     "legendFormat": "fsm.coordinate count"
    },
    {
     "expr": "avg(rate(consul_fsm_persist_count[${interval}]))",
     "legendFormat": "fsm.persist count"
    },
    {
     "expr": "avg(rate(consul_raft_fsm_apply_count[${interval}]))",
     "legendFormat": "fsm.apply count"
    },
    {
     "expr": "avg(rate(consul_fsm_register_count[${interval}]))",
     "legendFormat": "fsm.register count"
    },
    {
     "expr": "avg(rate(consul_fsm_deregister_count[${interval}]))",
     "legendFormat": "fsm.deregister count"
    },
    {
     "expr": "avg(rate(consul_fsm_session_count[${interval}]))",
     "legendFormat": "fsm.session count"
    }
   ]
  },
  {
   "title": "Top 5 Queried Services by Health",
   "type": "graph",
   "description": "This increments for each health query for the given service.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(consul_health_service_query_value) by (service))",
     "legendFormat": "{{ service }}"
    },
    {
     "expr": "topk(5, sum(rate(consul_health_service_query[5m])) by (service))",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 142 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{instance=~\".+\",name=~\"consul-.+\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}