{
 "title": "Hashicorp Vault",
 "description": " Hashicorp Vault Metrics",
 "tags": [ "vault" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(up{job=\"vault\"}, instance)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(up{job=\"vault\",instance=~\"$node:(.*)\"}, instance)"
    }
   },
   {
    "name": "mountpoint",
    "label": "Mount Point:",
    "query": {
     "query": "label_values(vault_secret_kv_count, mount_point)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Healthy Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"vault\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "avg without(instance) (vault_secret_kv_count)",
     "legendFormat": "{{ mount_point }}"
    }
   ]
  },
  {
   "title": "Number of Identity Entities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_identity_num_entities)"
    }
   ]
  },
  {
   "title": "Identity Entities Aliases by Method",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg without(instance) (vault_identity_entity_alias_count)",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(1 + vault_core_unsealed{})", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Number of Leases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(vault_expire_num_leases)" }
   ]
  },
  {
   "title": "Raft - Get Storage - pp",
   "type": "graph",
   "description": "The time to retrieve a value for a path.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_raft_storage_get{quantile=\"0.9\"}",
     "legendFormat": "{{instance}} get"
    }
   ]
  },
  {
   "title": "Raft - Put Storage - pp",
   "type": "graph",
   "description": "The time to retrieve a value for a path.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_raft_storage_put{quantile=\"0.9\"}",
     "legendFormat": "{{instance}} put"
    }
   ]
  },
  {
   "title": "Raft - List Storage - pp",
   "type": "timeseries",
   "description": "The time to retrieve a value for a path.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(count(vault_raft_storage_list{quantile=\"0.9\"}))",
     "legendFormat": "{{instance}} list"
    }
   ]
  },
  {
   "title": "Sealed Status - pp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "vault_core_unsealed+1", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Performance - pp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true
  },
  {
   "title": "Number of login requests over $vault_cluster,$api_url",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vault_core_handle_login_request_count",
     "legendFormat": "{{instance}} login request"
    }
   ]
  },
  {
   "title": "Number of requests over $vault_cluster,$api_cluster",
   "type": "graph",
   "description": "Duration of time taken by requests handled by Vault core",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_core_handle_request_count[1m]))",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "mountpoint",
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Operations in 5 minute" }
     ],
     "targets": [
      {
       "expr": "avg(increase(vault_route_create_${mountpoint}__count[5m]))",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(increase(vault_route_delete_${mountpoint}__count[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(increase(vault_route_read_${mountpoint}__count[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(increase(vault_route_list_${mountpoint}__count[5m]))",
       "legendFormat": "List"
      }
     ]
    },
    {
     "title": "Time of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "µs", "label": "Time of one operation" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum[1m]) / rate(vault_route_create_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum[1m]) / rate(vault_route_delete_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum[1m]) / rate(vault_route_read_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum[1m]) / rate(vault_route_list_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "List"
      }
     ]
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Operations in 5 minute" }
     ],
     "targets": [
      {
       "expr": "avg(increase(vault_route_create_${mountpoint}__count[5m]))",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(increase(vault_route_delete_${mountpoint}__count[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(increase(vault_route_read_${mountpoint}__count[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(increase(vault_route_list_${mountpoint}__count[5m]))",
       "legendFormat": "List"
      }
     ]
    },
    {
     "title": "Time of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "µs", "label": "Time of one operation" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum[1m]) / rate(vault_route_create_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum[1m]) / rate(vault_route_delete_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum[1m]) / rate(vault_route_read_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum[1m]) / rate(vault_route_list_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "List"
      }
     ]
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Operations in 5 minute" }
     ],
     "targets": [
      {
       "expr": "avg(increase(vault_route_create_${mountpoint}__count[5m]))",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(increase(vault_route_delete_${mountpoint}__count[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(increase(vault_route_read_${mountpoint}__count[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(increase(vault_route_list_${mountpoint}__count[5m]))",
       "legendFormat": "List"
      }
     ]
    },
    {
     "title": "Time of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "µs", "label": "Time of one operation" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum[1m]) / rate(vault_route_create_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum[1m]) / rate(vault_route_delete_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum[1m]) / rate(vault_route_read_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum[1m]) / rate(vault_route_list_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "List"
      }
     ]
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Operations in 5 minute" }
     ],
     "targets": [
      {
       "expr": "avg(increase(vault_route_create_${mountpoint}__count[5m]))",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(increase(vault_route_delete_${mountpoint}__count[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(increase(vault_route_read_${mountpoint}__count[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(increase(vault_route_list_${mountpoint}__count[5m]))",
       "legendFormat": "List"
      }
     ]
    },
    {
     "title": "Time of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "µs", "label": "Time of one operation" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum[1m]) / rate(vault_route_create_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum[1m]) / rate(vault_route_delete_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum[1m]) / rate(vault_route_read_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum[1m]) / rate(vault_route_list_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "List"
      }
     ]
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Operations in 5 minute" }
     ],
     "targets": [
      {
       "expr": "avg(increase(vault_route_create_${mountpoint}__count[5m]))",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(increase(vault_route_delete_${mountpoint}__count[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(increase(vault_route_read_${mountpoint}__count[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(increase(vault_route_list_${mountpoint}__count[5m]))",
       "legendFormat": "List"
      }
     ]
    },
    {
     "title": "Time of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "µs", "label": "Time of one operation" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum[1m]) / rate(vault_route_create_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum[1m]) / rate(vault_route_delete_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum[1m]) / rate(vault_route_read_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum[1m]) / rate(vault_route_list_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "List"
      }
     ]
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Operations in 5 minute" }
     ],
     "targets": [
      {
       "expr": "avg(increase(vault_route_create_${mountpoint}__count[5m]))",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(increase(vault_route_delete_${mountpoint}__count[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(increase(vault_route_read_${mountpoint}__count[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(increase(vault_route_list_${mountpoint}__count[5m]))",
       "legendFormat": "List"
      }
     ]
    },
    {
     "title": "Time of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "µs", "label": "Time of one operation" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum[1m]) / rate(vault_route_create_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum[1m]) / rate(vault_route_delete_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum[1m]) / rate(vault_route_read_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum[1m]) / rate(vault_route_list_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "List"
      }
     ]
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Operations in 5 minute" }
     ],
     "targets": [
      {
       "expr": "avg(increase(vault_route_create_${mountpoint}__count[5m]))",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(increase(vault_route_delete_${mountpoint}__count[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(increase(vault_route_read_${mountpoint}__count[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(increase(vault_route_list_${mountpoint}__count[5m]))",
       "legendFormat": "List"
      }
     ]
    },
    {
     "title": "Time of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "µs", "label": "Time of one operation" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum[1m]) / rate(vault_route_create_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum[1m]) / rate(vault_route_delete_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum[1m]) / rate(vault_route_read_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum[1m]) / rate(vault_route_list_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "List"
      }
     ]
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Operations in 5 minute" }
     ],
     "targets": [
      {
       "expr": "avg(increase(vault_route_create_${mountpoint}__count[5m]))",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(increase(vault_route_delete_${mountpoint}__count[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(increase(vault_route_read_${mountpoint}__count[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(increase(vault_route_list_${mountpoint}__count[5m]))",
       "legendFormat": "List"
      }
     ]
    },
    {
     "title": "Time of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "µs", "label": "Time of one operation" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum[1m]) / rate(vault_route_create_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum[1m]) / rate(vault_route_delete_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum[1m]) / rate(vault_route_read_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum[1m]) / rate(vault_route_list_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "List"
      }
     ]
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Operations in 5 minute" }
     ],
     "targets": [
      {
       "expr": "avg(increase(vault_route_create_${mountpoint}__count[5m]))",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(increase(vault_route_delete_${mountpoint}__count[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(increase(vault_route_read_${mountpoint}__count[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(increase(vault_route_list_${mountpoint}__count[5m]))",
       "legendFormat": "List"
      }
     ]
    },
    {
     "title": "Time of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "µs", "label": "Time of one operation" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum[1m]) / rate(vault_route_create_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum[1m]) / rate(vault_route_delete_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum[1m]) / rate(vault_route_read_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum[1m]) / rate(vault_route_list_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "List"
      }
     ]
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Operations in 5 minute" }
     ],
     "targets": [
      {
       "expr": "avg(increase(vault_route_create_${mountpoint}__count[5m]))",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(increase(vault_route_delete_${mountpoint}__count[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(increase(vault_route_read_${mountpoint}__count[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(increase(vault_route_list_${mountpoint}__count[5m]))",
       "legendFormat": "List"
      }
     ]
    },
    {
     "title": "Time of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "µs", "label": "Time of one operation" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum[1m]) / rate(vault_route_create_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum[1m]) / rate(vault_route_delete_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum[1m]) / rate(vault_route_read_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum[1m]) / rate(vault_route_list_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "List"
      }
     ]
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Operations in 5 minute" }
     ],
     "targets": [
      {
       "expr": "avg(increase(vault_route_create_${mountpoint}__count[5m]))",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(increase(vault_route_delete_${mountpoint}__count[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(increase(vault_route_read_${mountpoint}__count[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(increase(vault_route_list_${mountpoint}__count[5m]))",
       "legendFormat": "List"
      }
     ]
    },
    {
     "title": "Time of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "µs", "label": "Time of one operation" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum[1m]) / rate(vault_route_create_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum[1m]) / rate(vault_route_delete_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum[1m]) / rate(vault_route_read_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum[1m]) / rate(vault_route_list_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "List"
      }
     ]
    }
   ]
  },
  {
   "title": "Path Info: $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Operations in 5 minute" }
     ],
     "targets": [
      {
       "expr": "avg(increase(vault_route_create_${mountpoint}__count[5m]))",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(increase(vault_route_delete_${mountpoint}__count[5m]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(increase(vault_route_read_${mountpoint}__count[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(increase(vault_route_list_${mountpoint}__count[5m]))",
       "legendFormat": "List"
      }
     ]
    },
    {
     "title": "Time of Operations in \"$mountpoint\"",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "µs", "label": "Time of one operation" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum[1m]) / rate(vault_route_create_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum[1m]) / rate(vault_route_delete_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum[1m]) / rate(vault_route_read_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum[1m]) / rate(vault_route_list_${mountpoint}__count[1m]) * 1000)",
       "legendFormat": "List"
      }
     ]
    }
   ]
  },
  { "title": "CPU/Mem Info: $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Heap Objects Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_heap_objects{} / vault_runtime_malloc_count{})"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_num_goroutines{})"
    }
   ]
  },
  {
   "title": "Allocated MB",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(vault_runtime_alloc_bytes{})",
     "legendFormat": "$node"
    }
   ]
  },
  {
   "title": "Allocated MB - pp",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "vault_runtime_alloc_bytes{}", "legendFormat": "{{instance}} alloc" },
    { "expr": "vault_runtime_sys_bytes", "legendFormat": "{{instance}} sys" }
   ]
  },
  { "title": "Token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Available Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(vault_token_count)" }
   ]
  },
  {
   "title": "Tokens by Policy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_policy)",
     "legendFormat": "{{ policy }}"
    }
   ]
  },
  {
   "title": "Pending Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_token_create_count - vault_token_store_count)"
    }
   ]
  },
  {
   "title": "Tokens by TTL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_ttl)",
     "legendFormat": "{{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Tokens by Auth Method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_auth)",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Tokens Creation by Method & TTL",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(auth_method, creation_ttl) (vault_token_creation)",
     "legendFormat": "{{ auth_method }} - {{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Token Creation/Storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_create_count)",
     "legendFormat": "Create"
    },
    {
     "expr": "avg without(instance) (vault_token_store_count)",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Token Lookups",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "Lookups per second" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_token_lookup_count[1m]))",
     "legendFormat": "Lookups"
    }
   ]
  },
  { "title": "Audit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Log Request Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_request_failure[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Log Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 3, "y": 79 },
   "yaxes": [
    { "format": "short", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_audit_log_request_count[1m]))",
     "legendFormat": "Request "
    },
    {
     "expr": "avg(irate(vault_audit_log_response_count[1m]))",
     "legendFormat": "Response"
    },
    {
     "expr": "avg(irate(vault_core_handle_request_count[1m]))",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Consul Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 79 },
   "yaxes": [
    { "format": "short", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_consul_get_count[1m]))",
     "legendFormat": "GET"
    },
    {
     "expr": "avg(irate(vault_consul_put_count[1m]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "avg(irate(vault_consul_delete_count[1m]))",
     "legendFormat": "DELETE"
    },
    {
     "expr": "irate(vault_consul_list_count{instance=\"$node:$port\"}[1m])",
     "legendFormat": "LIST"
    }
   ]
  },
  {
   "title": "Log Response Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_response_failure[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  { "title": "Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Policy Set",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_policy_set_policy_count[1m]))",
     "legendFormat": "SET"
    }
   ]
  },
  {
   "title": "Policy Get",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(vault_policy_get_policy_count[1m]))",
     "legendFormat": "GET"
    }
   ]
  }
 ]
}